### ISSUE TITLE
Exception in DifferencesSideBySideAsHtml(string, string, bool, XmlDiffOptions);

### ISSUE THREAD

**Issue by rzuurmond** [lovettchris/xmldiff#3]
Exception in DifferencesSideBySideAsHtml(string, string, bool, XmlDiffOptions);

var view = new XmlDiffView();
var options = XmlDiffOptions.IgnoreChildOrder | XmlDiffOptions.IgnoreWhitespace;
var results = view.DifferencesSideBySideAsHtml(xmlSource, xmlChanged, false, options);

Reading from the MemoryStream fails

Results in exception:

This exception was originally thrown at this call stack:
    System.IO.StreamReader.StreamReader(System.IO.Stream, System.Text.Encoding, bool, int, bool)
    System.IO.StreamReader.StreamReader(System.IO.Stream, System.Text.Encoding)
    Microsoft.XmlDiffPatch.XmlDiffViewResults.PopulateReader(ref System.IO.MemoryStream)
    Microsoft.XmlDiffPatch.XmlDiffView.DifferencesSideBySideAsHtml(string, string, bool, Microsoft.XmlDiffPatch.XmlDiffOptions)
    XmlComparerTest.Comparer.Compare(string, string) in Comparer.cs
    XmlComparerTest.MainWindow.CompareFiles_OnClick(object, System.Windows.RoutedEventArgs) in MainWindow.xaml.cs
    System.Windows.RoutedEventHandlerInfo.InvokeHandler(object, System.Windows.RoutedEventArgs)
    System.Windows.EventRoute.InvokeHandlersImpl(object, System.Windows.RoutedEventArgs, bool)
    System.Windows.UIElement.RaiseEventImpl(System.Windows.DependencyObject, System.Windows.RoutedEventArgs)
    System.Windows.UIElement.RaiseEvent(System.Windows.RoutedEventArgs)

**Comment by lovettchris** [comment]
Fixed in version https://www.nuget.org/packages/LovettSoftware.XmlDiff/1.0.6
